name: Create Branch

on:
  workflow_dispatch:
    inputs:
      mission_name:
        description: 'Name of the mission'
        required: true
        type: string

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Create a new branch for the mission
      run: |
        git checkout -b ${{ inputs.mission_name }} master
        git push origin ${{ inputs.mission_name }}
