name: Create New Branch

on:
  # The workflow can be manually triggered using the UI or API
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Name of the new branch to create"
        required: true
        type: string

jobs:
  create-branch:
    runs-on: ubuntu-latest  # Specifies the runner to use
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Use the latest version of the checkout action
        with:
          fetch-depth: 0  # Fetch the entire history to allow branch creation

      - name: Create new branch
        run: |
          git checkout -b ${{ inputs.branch_name }}  # Create a new branch with the provided name

      - name: Push new branch
        run: |
          git push origin ${{ inputs.branch_name }}  # Push the new branch to the repository
